apiVersion: v1
kind: Service
metadata:
  name: aks-demo-service
spec:
  type: LoadBalancer # Exposes the service with an external IP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: aks-demo-app